version: "3.9"
services:
  apiserver:
    image: alpine:3.15.0
    environment:
      START_COMMAND: uvicorn app.main:app --reload
      UVICORN_HOST: 0.0.0.0
      IPS_DB_URL: postgresql://ips:ips@postgres/ips
      IPS_MQ_URL: amqp://guest:guest@rabbitmq/%2F
      IPS_STORAGE_PATH: /data
    volumes:
      - files:/data
      - ./src/main/python:/app:ro
      - ./requirements.txt:/requirements.txt:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
    ports:
      - "8000:8000"
    entrypoint: /entrypoint.sh
    depends_on:
      - postgres
      - rabbitmq
  worker:
    image: alpine:3.15.0
    environment:
      START_COMMAND: app.worker
      IPS_MQ_URL: amqp://guest:guest@rabbitmq/%2F
      IPS_STORAGE_PATH: /data
    volumes:
      - files:/data
      - ./src/main/python:/app:ro
      - ./requirements.txt:/requirements.txt:ro
      - ./entrypoint.sh:/entrypoint.sh:ro
    entrypoint: /entrypoint.sh
    depends_on:
      - rabbitmq
  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: ips
      POSTGRES_PASSWORD: ips
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.9.11-alpine
    volumes:
      - rabbitmq:/var/lib/rabbitmq
volumes:
  postgresql: {}
  postgresql_data: {}
  rabbitmq: {}
  files: {}
