# This file is only intended for development purposes. It mounts the source code
# directory into the containers and allows live reload.
---

version: "3.9"
services:
  apiserver:
    image: alpine:3.15.0
    working_dir: /app/src/main/python
    environment:
      START_COMMAND: uvicorn ips.main:app --reload
      UVICORN_HOST: 0.0.0.0
      IPS_DB_URL: postgresql://ips:ips@postgres/ips
      IPS_MQ_URL: amqp://guest:guest@rabbitmq/%2F
      IPS_STORAGE_PATH: /data
    volumes:
      - files:/data
      - ./:/app:ro
    ports:
      - "8000:8000"
    entrypoint: /app/entrypoint.sh
    depends_on:
      - postgres
      - rabbitmq
  worker:
    image: alpine:3.15.0
    working_dir: /app/src/main/python
    environment:
      START_COMMAND: ips.worker
      IPS_DB_URL: postgresql://ips:ips@postgres/ips
      IPS_MQ_URL: amqp://guest:guest@rabbitmq/%2F
      IPS_STORAGE_PATH: /data
    volumes:
      - files:/data
      - ./:/app:ro
    entrypoint: /app/entrypoint.sh
    depends_on:
      - postgres
      - rabbitmq
  alembic:
    image: alpine:3.15.0
    working_dir: /app
    environment:
      START_COMMAND: alembic upgrade head
      IPS_DB_URL: postgresql://ips:ips@postgres/ips
    volumes:
      - ./:/app:ro
    entrypoint: /app/entrypoint.sh
    depends_on:
      - postgres
  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: ips
      POSTGRES_PASSWORD: ips
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  rabbitmq:
    image: rabbitmq:3.9.11-alpine
    volumes:
      - rabbitmq:/var/lib/rabbitmq
volumes:
  postgresql: {}
  postgresql_data: {}
  rabbitmq: {}
  files: {}
