"""
Initial migration

Revision ID: 40d0ca042ce2
Revises: 
Create Date: 2021-12-25 19:24:56.906301

"""
from alembic import op
import sqlalchemy as sa
import ips.models


# revision identifiers, used by Alembic.
revision = "40d0ca042ce2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processing_jobs",
        sa.Column("uuid", ips.models.GUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "WAITING",
                "PROCESSING",
                "FINISHED",
                "FAILED",
                "ABORTED",
                name="processingstatus",
            ),
            nullable=False,
        ),
        sa.Column("output_uuid", ips.models.GUID(), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_processing_jobs_uuid"), "processing_jobs", ["uuid"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_processing_jobs_uuid"), table_name="processing_jobs")
    op.drop_table("processing_jobs")
    # ### end Alembic commands ###
