"""
Add original filename and Content-Type

Revision ID: a7cd45f9fd68
Revises: 40d0ca042ce2
Create Date: 2021-12-25 20:00:44.476722

"""
from alembic import op
import sqlalchemy as sa
import ips.models


# revision identifiers, used by Alembic.
revision = "a7cd45f9fd68"
down_revision = "40d0ca042ce2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "processing_jobs",
        sa.Column("original_filename", sa.Text(), server_default="", nullable=False),
    )
    op.add_column(
        "processing_jobs",
        sa.Column(
            "original_content_type", sa.Text(), server_default="", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("processing_jobs", "original_content_type")
    op.drop_column("processing_jobs", "original_filename")
    # ### end Alembic commands ###
